################################
# project configuration
################################

# C++ project
language: cpp
dist: trusty
sudo: false

################################
# build matrix
################################

matrix:
  include:

  # OSX / Clang

  - os: osx
    env: C_COMPILER=clang CXX_COMPILER=clang++
    osx_image: xcode7.3

  - os: osx
    env: C_COMPILER=clang CXX_COMPILER=clang++
    osx_image: xcode8.2

  # Linux / GCC

  - os: linux
    env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - ppa:george-edison55/cmake-3.x
        packages:
          - gcc-5
          - g++-5
          - cmake
          - xorg-dev
          - libgl1-mesa-dev

  # Linux / Clang

  - os: linux
    env: C_COMPILER=clang CXX_COMPILER=clang++
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
          - g++-5
          - xorg-dev
          - libgl1-mesa-dev

################################
# build script
################################

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER ..
  - make
