sudo: required
dist: trusty
language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update -q
  - sudo apt-get install cmake
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
