sudo: required
dist: trusty
language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
addons:
  apt:
    sources:
    - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
    - cmake
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install cmake; fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
