version: '0.1.0-{build}'
os: Visual Studio 2015
platform: x64
clone_depth: 3
configuration:
    - Release

before_build:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 Win64"

build_script:
    - cmake --build . --config Release
